class WorkingUnit:
    def __init__(self, id, name):
        self.name = name
        self.id = id
    
    def getWorkingUnitList():
        workingUnitList = []
        workingUnitList.append(WorkingUnit(24,"Enerji Enstitüsü"))
        workingUnitList.append(WorkingUnit(28,"Avrasya Yer Bilimleri Enstitüsü"))
        workingUnitList.append(WorkingUnit(29,"Bilişim Enstitüsü"))
        workingUnitList.append(WorkingUnit(56,"Afet Yönetimi Enstitüsü"))
        workingUnitList.append(WorkingUnit(3666,"Havacılık Enstitüsü"))
        workingUnitList.append(WorkingUnit(83,"Elektronik ve Haberleşme Mühendisliği"))
        workingUnitList.append(WorkingUnit(93,"Çevre Mühendisliği"))
        workingUnitList.append(WorkingUnit(96,"Gemi ve Deniz Teknolojisi Mühendisliği"))
        workingUnitList.append(WorkingUnit(98,"Endüstri Mühendisliği"))
        workingUnitList.append(WorkingUnit(100,"Endüstriyel Tasarım"))
        workingUnitList.append(WorkingUnit(101,"Fizik Mühendisliği"))
        workingUnitList.append(WorkingUnit(102,"Gemi İnşaatı ve Gemi Makinaları Mühendisliği"))
        workingUnitList.append(WorkingUnit(104,"Gıda Mühendisliği"))
        workingUnitList.append(WorkingUnit(106,"İnşaat Mühendisliği"))
        workingUnitList.append(WorkingUnit(107,"İşletme Mühendisliği"))
        workingUnitList.append(WorkingUnit(110,"Jeofizik Mühendisliği"))
        workingUnitList.append(WorkingUnit(111,"Jeoloji Mühendisliği"))
        workingUnitList.append(WorkingUnit(114,"Kimya Mühendisliği"))
        workingUnitList.append(WorkingUnit(116,"Maden Mühendisliği"))
        workingUnitList.append(WorkingUnit(117,"Makina Mühendisliği"))
        workingUnitList.append(WorkingUnit(118,"Matematik Mühendisliği"))
        workingUnitList.append(WorkingUnit(119,"Metalurji ve Malzeme Mühendisliği"))
        workingUnitList.append(WorkingUnit(120,"Mimarlık"))
        workingUnitList.append(WorkingUnit(123,"Meteoroloji Mühendisliği"))
        workingUnitList.append(WorkingUnit(126,"Peyzaj Mimarlığı"))
        workingUnitList.append(WorkingUnit(127,"Petrol ve Doğal Gaz Mühendisliği"))
        workingUnitList.append(WorkingUnit(130,"Şehir ve Bölge Planlama"))
        workingUnitList.append(WorkingUnit(132,"Tekstil Mühendisliği"))
        workingUnitList.append(WorkingUnit(133,"Uçak Mühendisliği"))
        workingUnitList.append(WorkingUnit(135,"Uzay Mühendisliği"))
        workingUnitList.append(WorkingUnit(136,"Moleküler Biyoloji ve Genetik"))
        workingUnitList.append(WorkingUnit(142,"Geomatik Mühendisliği"))
        workingUnitList.append(WorkingUnit(162,"Cevher Hazırlama Mühendisliği"))
        workingUnitList.append(WorkingUnit(171,"İç Mimarlık"))
        workingUnitList.append(WorkingUnit(939,"Bilgisayar Mühendisliği"))
        workingUnitList.append(WorkingUnit(941,"Deniz Ulaştırma İşletme Mühendisliği"))
        workingUnitList.append(WorkingUnit(942,"Gemi Makinaları İşletme Mühendisliği"))
        workingUnitList.append(WorkingUnit(947,"Elektrik Mühendisliği"))
        workingUnitList.append(WorkingUnit(1015,"Ekonomi"))
        workingUnitList.append(WorkingUnit(1018,"Temel Bilimler"))
        workingUnitList.append(WorkingUnit(1019,"Sosyoloji"))
        workingUnitList.append(WorkingUnit(1455,"Kontrol ve Otomasyon Mühendisliği"))
        workingUnitList.append(WorkingUnit(3704,"Yapay Zeka Ve Veri Mühendisliği"))
        workingUnitList.append(WorkingUnit(46,"Kimya"))
        return workingUnitList
    